chore: another test thing

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -45,10 +45,10 @@ include:
   - local: .gitlab/ci/build.gitlab-ci.yml
   - local: .gitlab/ci/lint.gitlab-ci.yml
   - local: .gitlab/ci/test.gitlab-ci.yml
+  - local: .gitlab/ci/evaluate.gitlab-ci.yml
   - local: .gitlab/ci/performance.gitlab-ci.yml
   - local: .gitlab/ci/release.gitlab-ci.yml
   - local: .gitlab/ci/ingest.gitlab-ci.yml
-  - local: .gitlab/ci/evaluate.gitlab-ci.yml
   - template: Jobs/Container-Scanning.latest.gitlab-ci.yml
   - template: Jobs/Dependency-Scanning.latest.gitlab-ci.yml
   - template: Jobs/SAST.latest.gitlab-ci.yml
@@ -96,6 +96,23 @@ cache:
     - poetry self add poetry-plugin-export
     - poetry export -f requirements.txt --output requirements.txt --without-hashes
     - poetry config --list
+
+.langsmith_evaluation:
+  stage: evaluate
+  needs:
+    - build:ingest-image
+    - poetry
+  services:
+   - name: ${TARGET_IMAGE}
+     alias: ai-gateway
+  script:
+    - |
+      if [ -z "$PROMPT_ID" ] || [ -z "$PROMPT_VERSION" ] || [ -z "$DATASET_NAME" ]; then
+        echo "Error: Required variables not set. Please define PROMPT_ID, PROMPT_VERSION, and DATASET_NAME."
+        exit 1
+      fi
+      echo "Running evaluation with PROMPT_ID=${PROMPT_ID}, PROMPT_VERSION=${PROMPT_VERSION}, DATASET_NAME=${DATASET_NAME}"
+      poetry run python eval ${PROMPT_ID} ${PROMPT_VERSION} ${DATASET_NAME}
 
 .docker:
   image: docker:${DOCKER_VERSION}
