chore: move enforce prompt versioning
moves to test before validating build

diff --git a/.gitlab/ci/test.gitlab-ci.yml b/.gitlab/ci/test.gitlab-ci.yml
--- a/.gitlab/ci/test.gitlab-ci.yml
+++ b/.gitlab/ci/test.gitlab-ci.yml
@@ -39,3 +39,27 @@ tests:integration:
     CI_DEBUG_SERVICES: true
   script:
     - make test-integration
+
+test:enforce_prompt_versioning:
+  stage: test
+  needs:
+    - build-docker-model-gateway
+  variables:
+    PROMPT_DEFINTIONS_DIR: "ai_gateway/prompts/definitions"
+  script:
+    - apk add --no-cache git
+    - |
+      changed_files=$(git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA -- '${PROMPT_DEFINTIONS_DIR}*.yml')
+      for file in $changed_files; do
+        if [[ ! $file =~ -alpha\.yml$ && ! $file =~ -beta\.yml$ && ! $file =~ -rc\.yml$ ]]; then
+          echo "Error: Changes to stable prompt file $file are not allowed."
+          exit 1
+        fi
+      done
+    - echo "All changes are in allowed files."
+  rules:
+    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
+    - if: $CI_PIPELINE_SOURCE == "schedule"
+    - if: $CI_PIPELINE_SOURCE == "push"
+      changes:
+        - "${PROMPT_DEFINTIONS_DIR}*.yml"
